python denoising.py --task denoising \
                      --folder_path '../data/Set9' \
                      --save_folder '/path/to/folder/noise_fitting' \
                      --imsize -1 \
                      --model_type DD \
                      --progressive True \
                      --in_size 16 16 \
                      --out_chns 3 \
                      --num_iters 3000 \
                      --norm_func bn \
                      --noise_sigma 25 \
                      --filter_size_down 3 \
                      --filter_size_up 3 \
                      --num_layers 6 \
                      --num_skips 0 \
                      --need_sigmoid True \
                      --loss_func mse \
                      --freq_loss_func moment_matching \
                      --optimizer adam \
                      --decay_lr False \
                      --exp_weight 0 \
                      --noise_type u \
                      --noise_method noise \
                      --special bilinearUp\
                      --prune_type None \
                      --reg_type 0 \
                      --decay 1e-8 0 \
                      --reg_noise_std '0' \
                      --upsample_mode bilinear \
                      --act_func ReLU \
                      --pad zero \
                      --dim 128 \
                      --lr 0.01                       
            
