python train_unsup.py --task denoising \
                      --folder_path data/denoising/ \
                      --model_type DIP \
                      --progressive False \
                      --meta_pruning True \
                      --meta_img_idx 0 2 4 6 \
                      --num_iters 3000 \
                      --norm_func bn \
                      --noise_sigma 25 \
                      --filter_size_down 5 \
                      --filter_size_up 3 \
                      --num_skips 2 \
                      --need_sigmoid True \
                      --loss_func mse \
                      --num_scales 8 \
                      --optimizer adam \
                      --decay_lr False \
                      --step_size 50 \
                      --gamma 0.55 \
                      --special DIP_withNoise_meta_pruning\
                      --prune_type HS \
                      --reg_type 3 \
                      --decay 0.0000001 \
                      --reg_noise_std '1/30' \
                      --upsample_mode bilinear \
                      --act_func ReLU \
                      --pad zero \
                      --dim 32 \
                      --lr 0.01                       
            
