python train_unsup.py --task denoising \
                      --folder_path '../data/denoising' \
                      --save_folder '/mnt/yaplab/data/yilinliu/saves/lowpass_test' \
                      --imsize -1 \
                      --model_type DD_orig \
                      --progressive False \
                      --in_size 512 512 \
                      --out_chns 3 \
                      --num_iters 3000 \
                      --norm_func bn \
                      --noise_sigma 25 \
                      --filter_size_down 3 \
                      --filter_size_up 3 \
                      --num_layers 6 \
                      --num_skips 0 \
                      --need_sigmoid True \
                      --loss_func mse \
                      --freq_loss_func moment_matching \
                      --num_scales 2 \
                      --optimizer adam \
                      --decay_lr False \
                      --step_size 50 \
                      --gamma 0.55 \
                      --morph_lbda 1e-5 \
                      --exit_layer_idx_prior 0.5 \
                      --min_tau 0.4 \
                      --exp_weight 0.99 \
                      --special 6Layerss_lowpass_noReg\
                      --prune_type None \
                      --reg_type 0 \
                      --decay 1e-8 0 \
                      --freq_lbda 0 \
                      --reg_noise_std '0' \
                      --upsample_mode bilinear \
                      --act_func ReLU \
                      --pad zero \
                      --dim 128 \
                      --lr 0.01                       
            
