python mri.py --task mri_knee \
                      --model_type ConvDecoder \
                      --folder_path '/shenlab/lab_stor/yilinliu/fastMRI_datasets/tmp/' \
                      --save_folder '/mnt/yaplab/data/yilinliu/saves/mri_knee/MICCAI' \
                      --progressive True \
                      --pruning_sensitivity 0.01 \
                      --num_scales 5 \
                      --num_layers 7 \
                      --need_sigmoid False \
                      --filter_size_down 3 \
                      --filter_size_up 3 \
                      --num_skips 5 \
                      --loss_func l1 \
                      --optimizer adam \
                      --jacobian_lbda 0 \
                      --jacobian_eval 0 \
                      --Lipschitz_constant 1 \
                      --Lipschitz_reg 0 \
                      --deepspline_lbda 0.0 \
                      --deepspline_lipschitz False \
                      --verbose False \
                      --num_power_iterations 10 \
                      --tv_weight 0 \
                      --noise_method 'noise' \
                      --noise_type 'u' \
                      --iters_print_acc 50 \
                      --special 256chns_nearest\
                      --prune_type 'None' \
                      --decay 0.0000001 0.0 \
                      --reg_type 0 \
                      --need_dropout False \
                      --reg_noise_std 0 \
                      --sr 0.0 \
                      --upsample_mode nearest \
                      --act_func ReLU \
                      --pad zero \
                      --input_dim 256 \
                      --dim 256 \
                      --exp_weight 0 \
                      --num_iters 3000 \
                      --lr 0.008
          
                    
            
